// const numbers =[21,10,30,41]
// let names =["hema","riya","trisha","rish"]
// let k = document.getElementById('key')
// let but = document.getElementById('search')
//  let r= document.getElementById("stud")
//  let btn = document.getElementById("sn")

// function pfunction(){
//     if(numbers.indexOf(Number(k.value))==-1){
// document.write(k.value+"<b>failed<b>")
//     }
//     else{
//         document.write("<b>succes"+(numbers.indexOf(Number(k.value)))+"positon </b>")
//     }
// }


// but.addEventListener("click",pfunction)


// {/* <script>
    
// const numbers =[21,10,30,41]
// let names =["hema","riya","trisha","rish"]

//  let r= document.getElementById("stud")
//  let btn = document.getElementById("sn")

//     function searchname(){
//         if(names.indexOf(String(r.value))==-1){
//     document.write(r.value+"<b>yup present</b>")
//         }else{
//             document.write("<b> uff present at "+(names.indexOf(String(r.value)))+" positon </b>")
//         }
//     }


//     btn.addEventListener("click",searchname)</script>
// <!-- <scrip src="./ARRAY.JS"></script> -->
//  */}


    
// const numbers =[21,10,30,41]
// let names =["hema","riya","trisha","rish"]

//  let r= document.getElementById("stud")
//  let btn = document.getElementById("sn")

//     function searchname(){
//         if(names.indexOf(String(r.value))==-1){
//     document.write(r.value+"<b>uff absent </b>")
//         }else{
//             document.write("<b> yup present at "+(names.indexOf(String(r.value)))+" positon </b>")
//         }
//     }


//     btn.addEventListener("click",searchname)



















